version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      react-packages:
        patterns:
          - "react"
          - "react-dom"
      stylelint-packages:
        patterns:
          - "stylelint*"
      vite-packages:
        patterns:
          - "@vitejs/*"
          - "vite"
      vitest-packages:
        patterns:
          - "vitest*"
          - "@vitest/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
