version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      development:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "react"
          - "react-dom"
