dist: jammy
language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: lint
      name: eslint
      script: npm run lint
    - stage: lint
      name: stylelint
      script: npm run lint:css
    - stage: build
      name: vite
      script: npm run build
stages:
  - lint
  - build
