dist: jammy
language: node_js
node_js:
  - lts/*
jobs:
  include:
    - stage: lint
      name: lint
      script: npm run lint
    - stage: lint
      name: lint:css
      script: npm run lint:css
    - stage: build
      name: build
      script: npm run build
stages:
  - lint
  - build
