name: push
permissions:
  contents: read
on:
  push:
    branches:
      - main
jobs:
  integrate:
    uses: umts/shared-workflows/.github/workflows/integrate-vite.yml@15c71ed09491317e4eee2a082634b70a245b5651
  deploy:
    needs: integrate
    permissions:
      pages: write
      id-token: write
    uses: umts/shared-workflows/.github/workflows/pages-vite.yml@15c71ed09491317e4eee2a082634b70a245b5651
